- op: add
  path: /spec/template/spec/containers/0/args
  value: ["newrelic-admin run-program uwsgi \
  --static-map /static=/openedx/staticfiles/ \
  --static-map /media=/openedx/media/ \
  --http 0.0.0.0:8000 --thunder-lock \
  --single-interpreter --enable-threads \
  --processes=${UWSGI_WORKERS:-2} \
  --buffer-size=8192 \
  --wsgi-file $SERVICE_VARIANT/wsgi.py"]
- op: add
  path: /spec/template/spec/containers/0/command
  value: ["/bin/bash", "-c"]
- op: add
  path: /spec/template/spec/containers/0/env/0
  value:
    name: NEW_RELIC_CONFIG_FILE
    value: /openedx/newrelic/newrelic.ini
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/0
  value:
    mountPath: /openedx/newrelic/
    name: newrelic-ini
- op: add
  path: /spec/template/spec/volumes/0
  value:
    configMap:
      name: newrelic-cm
    name: newrelic-ini
